from django.urls import path
from .views import (DocumentsListing,
                    DocumentsUpload,
                    DocumentDetails,
                    RemoveDocument,
                    SourceDocument,
                    SearchableDocument,
                    ExportDocuments,
                    VerifyExistingDocuments,
                    PushNotification,
                    QualityKpisList,
                    QualityKpiDetails,
                    DocumentTree,
                    AdminUpload,
                    PaymentTermsList,
                    DocumentPrice,
                    AdminDownload,
                    PaymentTermDetails,
                    ExportPaymentTerms)

urlpatterns = [
    path(r'export-documents/', ExportDocuments.as_view(), name="export_documents"),
    path(r'export-payment-terms/', ExportPaymentTerms.as_view(), name="export_payment_terms"),
    path(r'document/', DocumentDetails.as_view(), name="documents_details"),
    path(r'documents/', DocumentsListing.as_view(), name="documents_list"),
    path(r'document-upload/', DocumentsUpload.as_view(), name="document_upload"),
    path(r'remove-document/', RemoveDocument.as_view(), name="remove_document"),
    path(r'verify-document/', VerifyExistingDocuments.as_view(), name="verify_existing_document"),
    path(r'source-document/', SourceDocument.as_view(), name="source_document"),
    path(r'searchable-document/', SearchableDocument.as_view(), name="searchable_document"),
    path(r'push-notification/', PushNotification.as_view(), name="push-notification"),
    path(r'quality-kpi/', QualityKpiDetails.as_view(), name="quality_kpi_details"),
    path(r'quality-kpis/', QualityKpisList.as_view(), name="quality_kpis_list"),
    path(r'payment-term/', PaymentTermDetails.as_view(), name="payment_terms_details"),
    path(r'payment-terms/', PaymentTermsList.as_view(), name="payment_terms_list"),
    path(r'document-price/', DocumentPrice.as_view(), name="price_list"),
    path(r'document-tree/', DocumentTree.as_view(), name="document_tree"),
    path(r'admin-upload/', AdminUpload.as_view(), name="admin_upload"),
    path(r'admin-download/', AdminDownload.as_view(), name="admin_download"),
]
